"""crear esquema inicial de metadatos

Revision ID: 42151b55aae0
Revises: 
Create Date: 2026-10-05 21:11:04.398574+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# Identificadores de la revisión, usados por Alembic.
revision: str = '42151b55aae0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acl_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('can_execute', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_entries_resource_id'), 'acl_entries', ['resource_id'], unique=False)
    op.create_index(op.f('ix_acl_entries_subject_id'), 'acl_entries', ['subject_id'], unique=False)
    op.create_table('datanodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'SUSPECT', 'OFFLINE', name='nodestatus'), nullable=False),
    sa.Column('free_space_bytes', sa.BigInteger(), nullable=False),
    sa.Column('last_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['directories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_directory_parent_name')
    )
    op.create_index(op.f('ix_directories_owner_id'), 'directories', ['owner_id'], unique=False)
    op.create_index(op.f('ix_directories_parent_id'), 'directories', ['parent_id'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('directory_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'AVAILABLE', 'FAILED', 'DELETING', name='filestatus'), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['directories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('directory_id', 'name', name='uq_file_directory_name')
    )
    op.create_index(op.f('ix_files_directory_id'), 'files', ['directory_id'], unique=False)
    op.create_index(op.f('ix_files_owner_id'), 'files', ['owner_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('used_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REPLICATING', 'COMMITTED', 'FAILED', name='blockstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'version', 'block_index', name='uq_block_file_version_index')
    )
    op.create_index(op.f('ix_blocks_file_id'), 'blocks', ['file_id'], unique=False)
    op.create_table('file_handles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle_token', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('READ', 'WRITE', name='filehandlemode'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_handles_file_id'), 'file_handles', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_handles_handle_token'), 'file_handles', ['handle_token'], unique=True)
    op.create_table('block_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('datanode_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PRIMARY', 'BACKUP', name='replicarole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REPLICATING', 'COMMITTED', 'FAILED', name='blockstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['datanode_id'], ['datanodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'datanode_id', name='uq_location_block_datanode')
    )
    op.create_index(op.f('ix_block_locations_block_id'), 'block_locations', ['block_id'], unique=False)
    op.create_index(op.f('ix_block_locations_datanode_id'), 'block_locations', ['datanode_id'], unique=False)
    op.create_table('file_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('handle_id', sa.Integer(), nullable=True),
    sa.Column('lock_type', sa.Enum('WRITE', name='locktype'), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['handle_id'], ['file_handles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_locks_file_id'), 'file_locks', ['file_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios de esta revisión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_locks_file_id'), table_name='file_locks')
    op.drop_table('file_locks')
    op.drop_index(op.f('ix_block_locations_datanode_id'), table_name='block_locations')
    op.drop_index(op.f('ix_block_locations_block_id'), table_name='block_locations')
    op.drop_table('block_locations')
    op.drop_index(op.f('ix_file_handles_handle_token'), table_name='file_handles')
    op.drop_index(op.f('ix_file_handles_file_id'), table_name='file_handles')
    op.drop_table('file_handles')
    op.drop_index(op.f('ix_blocks_file_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_files_owner_id'), table_name='files')
    op.drop_index(op.f('ix_files_directory_id'), table_name='files')
    op.drop_table('files')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_directories_parent_id'), table_name='directories')
    op.drop_index(op.f('ix_directories_owner_id'), table_name='directories')
    op.drop_table('directories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('datanodes')
    op.drop_index(op.f('ix_acl_entries_subject_id'), table_name='acl_entries')
    op.drop_index(op.f('ix_acl_entries_resource_id'), table_name='acl_entries')
    op.drop_table('acl_entries')
    # ### end Alembic commands ###
